import './app-body.html';
import './app-body.js';
import './app-not-found.html';
import './cas-login.html'
import './cas-login';
import './footer.html';
import './header.html';
import './home-dropdown.html';
import './home-dropdown';
import './if-logged-in.html';
import './if-logged-in.js';
import './loading.html';
import './not-authorized.html';
import './profile-dropdown.html';
import './profile-dropdown';
